# config file for varicity
# you may alter this file before running the program
# pick your color at https://htmlcolorcodes.com/

building:
  padding: 0.2
  colors:
    # outline: "#145a32" # dark green
    # edges: "#a569bd" # light purple
    faces: # ordered by importance, descending : in case of conflict, the first color to match will be displayed
      - name: "!HOTSPOT"
        color: "#555555"
      - name: "VP"
        color: "#FF6F33"
      - name: "STRATEGY"
        color: "#17202a" # black
      - name: "FACTORY"
        color: "#7d3c98" # purple
      - name: "INTERFACE"
        color: "#e67e22" # orange
      - name: "ABSTRACT"
        color: "#2c3e50" # dark blue
      - name: "CLASS"
        color: "#335DFF"

    edges:
      - name: "API"
        color: "#000000"

    outlines:
#      - name: "API"
#        color: "#FF0000"
# - name: "CLASS"
# color: "#000000"

district:
  padding: 0
  colors:
    # outline: "#145a32" # dark green
    # edges: "#a569bd" # light purple
    faces:
      - name: "PACKAGE"
        color: "#801A2E"
      - name: "VP"
        color: "#1A8039"

link:
  colors:
    - name: "IMPLEMENTS"
      color: "#ef2222"
    - name: "EXTENDS"
      color: "#3f97ff"
    - name: "DUPLICATES"
      color: "#2B914A"
    - name: "INSTANTIATE"
      color: "#1A8039"
  display:
    air_traffic:
      - "IMPLEMENTS"
      - "EXTENDS"
    underground_road:
      - "INSTANTIATE"

hierarchy_links:
  - "INSTANTIATE"

blacklist: #all classes that must not appear

api_classes: #all API classes
  abstract_decorator:
    - "ChristmasTree"
  decorator:
    - "com.iluwatar.decorator.Troll"
  density:
    - "Shape"
    - "Renderer"
  factory:
    - "Shape"
  generic_decorator:
    - "ChristmasTree"
    - "TreeDecorator"
  attribute_composition_factory:
    - "Dataset"
    - "Value"
    - "DefaultPieDataset"
  generics:
    - "MyPair"
  inheritance:
    - "Superclass"
  multiple_patterns:
    - "Shape"
    - "Factory"
  strategy:
    - "Strategy"
  strategy_with_method_parameter:
    - "Strategy"
  template:
    - "Algorithm"

variables: #variables to be used for width and height of a building
  width: "nbConstructorVariants"
  height: "nbMethodVariants"

orientation: "IN_OUT"

default_level: 1